#Enabling https below
#MORE about it on https://java-master.com/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-https-%D0%B2-spring-boot/
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: FuckSSLPass5
    key-password: FuckSSLPass5